{
  "formatVersion": "1.1",
  "component": {
    "group": "sh.swifttui",
    "module": "android-host",
    "version": "0.14.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.08.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-host-0.14.0.aar",
          "url": "android-host-0.14.0.aar",
          "size": 267148,
          "sha512": "632e335e4d37c8e1478b174f9de62b0d53891fc0481b2df6d70224e3b392e2da2275f6f951762e1dd51ce558a28e11e2a50f4b540e1c1f1e1053825d8a2c718b",
          "sha256": "d708781caa14d8b6298470bb912900aace08628e22cb2a6a80d4aea170ee9424",
          "sha1": "aba0384fb9ddde0a060a557077c5aba107a00f24",
          "md5": "96ba617400286b29fb98126a7f85dff7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.08.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-host-0.14.0.aar",
          "url": "android-host-0.14.0.aar",
          "size": 267148,
          "sha512": "632e335e4d37c8e1478b174f9de62b0d53891fc0481b2df6d70224e3b392e2da2275f6f951762e1dd51ce558a28e11e2a50f4b540e1c1f1e1053825d8a2c718b",
          "sha256": "d708781caa14d8b6298470bb912900aace08628e22cb2a6a80d4aea170ee9424",
          "sha1": "aba0384fb9ddde0a060a557077c5aba107a00f24",
          "md5": "96ba617400286b29fb98126a7f85dff7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-host-0.14.0-sources.jar",
          "url": "android-host-0.14.0-sources.jar",
          "size": 43315,
          "sha512": "d5bc8906821287fe5c1a9ecd1f3da98235193e065e5a59b6d16a6b46389165cc8a7d39909e0706459c38f2b1c0e8f0f8764a6a473d415d77f49cc1491ead1a51",
          "sha256": "e93e3823a7dd116094f5195ec251713f97269a7d416daf0e230a3e054731f76a",
          "sha1": "e608383f10e146cd3f0114a898a76fd59545397b",
          "md5": "71ea328537905944744ce1c69a02b1b1"
        }
      ]
    }
  ]
}
