{
  "formatVersion": "1.1",
  "component": {
    "group": "sh.swifttui",
    "module": "android-host",
    "version": "0.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.08.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-host-0.12.0.aar",
          "url": "android-host-0.12.0.aar",
          "size": 284361,
          "sha512": "a54d082053173a9500a1732765acb8c0722b82ffadae357011e6b55ae0b604a8ef0e86b369548af987567c08234682afd0e587e70e59759dd0cd0d4cd43534ca",
          "sha256": "e5813567fdf1cc86f4e7bd1415be0efb8b171dcad61ebfb40726116fae858063",
          "sha1": "5294487d7fc5b69f5c9c3f0d94c070dd5cdacca2",
          "md5": "75f0ef65dd48384128dabe430f636d44"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.08.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-host-0.12.0.aar",
          "url": "android-host-0.12.0.aar",
          "size": 284361,
          "sha512": "a54d082053173a9500a1732765acb8c0722b82ffadae357011e6b55ae0b604a8ef0e86b369548af987567c08234682afd0e587e70e59759dd0cd0d4cd43534ca",
          "sha256": "e5813567fdf1cc86f4e7bd1415be0efb8b171dcad61ebfb40726116fae858063",
          "sha1": "5294487d7fc5b69f5c9c3f0d94c070dd5cdacca2",
          "md5": "75f0ef65dd48384128dabe430f636d44"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-host-0.12.0-sources.jar",
          "url": "android-host-0.12.0-sources.jar",
          "size": 36546,
          "sha512": "c96f4ff840a363f4c81401cce3502ad3befbb9530897ce3a75545567dae35d9093ff31c383e1ed505ac509a7dcceb43ea3d0ccc02bcb29cf9184d04fd364bc44",
          "sha256": "cea0d82f8dd46fe978ca3a4415b0953d1d9938b28be8325bf94b85c2592ce5a5",
          "sha1": "7ffbd7389725976787ad5b2731a34c52c1c15c8f",
          "md5": "b3113b6204cf1f28370b35912188285c"
        }
      ]
    }
  ]
}
