{
  "formatVersion": "1.1",
  "component": {
    "group": "sh.swifttui",
    "module": "android-host",
    "version": "0.0.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.05.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-host-0.0.21.aar",
          "url": "android-host-0.0.21.aar",
          "size": 231752,
          "sha512": "be49e6c36a1a40cfe307a36a5237c3a01fd0859726edfd748fe60067f52f6dd167846c24f816ec7283d280650ac761cc5619f364feb69410091b1af2ce4d5a6e",
          "sha256": "43df41ad0563dc480bcbe5b7a75d2fbde1003ad111cec0c63be45bebc6cb8d2c",
          "sha1": "83c96a755ac7ce269d644dbafc5a6b44b5271f7b",
          "md5": "d743b3339411f1a8e7888d90b82d9790"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.05.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-host-0.0.21.aar",
          "url": "android-host-0.0.21.aar",
          "size": 231752,
          "sha512": "be49e6c36a1a40cfe307a36a5237c3a01fd0859726edfd748fe60067f52f6dd167846c24f816ec7283d280650ac761cc5619f364feb69410091b1af2ce4d5a6e",
          "sha256": "43df41ad0563dc480bcbe5b7a75d2fbde1003ad111cec0c63be45bebc6cb8d2c",
          "sha1": "83c96a755ac7ce269d644dbafc5a6b44b5271f7b",
          "md5": "d743b3339411f1a8e7888d90b82d9790"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-host-0.0.21-sources.jar",
          "url": "android-host-0.0.21-sources.jar",
          "size": 23523,
          "sha512": "f5802a75f12ca37d8592e2a2a1acbdf1df49cda7309ff964c58203b350f13f0b60e40c6e8450ee0754789774b9c7136febf6090db5516261267edaa2e2fe86f1",
          "sha256": "a80c53c280d4bb522e80adfa42547fff0c6b1d4005b2498ab6eb5de10470c9ad",
          "sha1": "26b3d662c29af7ba42afb37f38cc0bd8894e369c",
          "md5": "edbe06affa7f695ffa47131bf10cef52"
        }
      ]
    }
  ]
}
