{
  "formatVersion": "1.1",
  "component": {
    "group": "sh.swifttui",
    "module": "android-host",
    "version": "0.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.05.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-host-0.4.5.aar",
          "url": "android-host-0.4.5.aar",
          "size": 271289,
          "sha512": "49310f91bb4c3341a840417e6836a984f0b44324ca3c8bcb4c2d5f5ef464fad6616e862ac570f653721a14de784d9660faa2678abcfdbb5a8ba3dc5f1f39a583",
          "sha256": "365456988e5aaf961c4deaf15b788767906e97e8c3b9e31a15ea253db3511abc",
          "sha1": "c1e5c180e05431906624a82c0500d011f355e4a3",
          "md5": "1907b79b926ab555ebb59a52799f7668"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.05.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-host-0.4.5.aar",
          "url": "android-host-0.4.5.aar",
          "size": 271289,
          "sha512": "49310f91bb4c3341a840417e6836a984f0b44324ca3c8bcb4c2d5f5ef464fad6616e862ac570f653721a14de784d9660faa2678abcfdbb5a8ba3dc5f1f39a583",
          "sha256": "365456988e5aaf961c4deaf15b788767906e97e8c3b9e31a15ea253db3511abc",
          "sha1": "c1e5c180e05431906624a82c0500d011f355e4a3",
          "md5": "1907b79b926ab555ebb59a52799f7668"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-host-0.4.5-sources.jar",
          "url": "android-host-0.4.5-sources.jar",
          "size": 34204,
          "sha512": "08a1e7b19bce0d46277c96e4559b6eecfe9bd8ed1fa623140d11fe89a2e1b1c3a822e308820443f1f25828ab21c8ecd17517d1b49afb933a7d377e91a0840cc3",
          "sha256": "5001ada4fd408537daa9478ce212b608c64269a43a1891e72222f598c4e3be2a",
          "sha1": "73c9f2ad69cb11a24725df1256d2683f7f659f2a",
          "md5": "0ecdb0f9b83eb8f384596ce6e1dc6dfc"
        }
      ]
    }
  ]
}
