{
  "formatVersion": "1.1",
  "component": {
    "group": "sh.swifttui",
    "module": "android-host",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.05.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-host-0.2.0.aar",
          "url": "android-host-0.2.0.aar",
          "size": 244064,
          "sha512": "599e6d7ae8d7ec081ed3f42ad8a69ae36a6dd3ad9e7329a4014770e493cbd87b018badbc488a1d189128ee0d5442ad2e31e4b4f2c208f1311b7b7ea5b4b3dcf5",
          "sha256": "6d27c004622f1df18f09049d1da9e3d8f2083a9a6508c574f831b13eb3aa7370",
          "sha1": "47ef19a14c2533764908257bf5ba7231e8ca8c60",
          "md5": "a8610410b3972e6dae4cec8c76a6d989"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.05.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-host-0.2.0.aar",
          "url": "android-host-0.2.0.aar",
          "size": 244064,
          "sha512": "599e6d7ae8d7ec081ed3f42ad8a69ae36a6dd3ad9e7329a4014770e493cbd87b018badbc488a1d189128ee0d5442ad2e31e4b4f2c208f1311b7b7ea5b4b3dcf5",
          "sha256": "6d27c004622f1df18f09049d1da9e3d8f2083a9a6508c574f831b13eb3aa7370",
          "sha1": "47ef19a14c2533764908257bf5ba7231e8ca8c60",
          "md5": "a8610410b3972e6dae4cec8c76a6d989"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-host-0.2.0-sources.jar",
          "url": "android-host-0.2.0-sources.jar",
          "size": 29358,
          "sha512": "c11529a6f4d8f93eed0938e0649da6548c8619f852a2c3f530e495ff8e00ce4daebfd8ded063e32cf50e13421ba92dce1c0967cd8da091694ffdc22fa53e67f8",
          "sha256": "120d4f8b3ca732306d33faf84ed155916e1a3b8633e216bb7834814764e7f15f",
          "sha1": "78ed5a7256610b7b60a17d66421749fbf4f825dc",
          "md5": "c999c510229709f9008e60f62f647f3b"
        }
      ]
    }
  ]
}
