{
  "formatVersion": "1.1",
  "component": {
    "group": "sh.swifttui",
    "module": "android-plugin",
    "version": "0.13.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "android-plugin-0.13.4.jar",
          "url": "android-plugin-0.13.4.jar",
          "size": 64228,
          "sha512": "d8ba913ac755db2631d46c1afb471c44e64a2aedddfa5004bae0aff17fbb524a86b7a99d37c699989b0b811621620e67607deb1487abfb1513c2cd94a2c09cf2",
          "sha256": "b6c3133b849dafbdc58a4ae11e7cbb0d8a2e46c944050f8531dd7249633e9398",
          "sha1": "7a5e69d7cce1e6ab589e7b3e0fcc26650781b460",
          "md5": "26dfb517b8df67b00307da714892d25f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "android-plugin-0.13.4.jar",
          "url": "android-plugin-0.13.4.jar",
          "size": 64228,
          "sha512": "d8ba913ac755db2631d46c1afb471c44e64a2aedddfa5004bae0aff17fbb524a86b7a99d37c699989b0b811621620e67607deb1487abfb1513c2cd94a2c09cf2",
          "sha256": "b6c3133b849dafbdc58a4ae11e7cbb0d8a2e46c944050f8531dd7249633e9398",
          "sha1": "7a5e69d7cce1e6ab589e7b3e0fcc26650781b460",
          "md5": "26dfb517b8df67b00307da714892d25f"
        }
      ]
    }
  ]
}
